
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PT_COMA = 6;
  public static final int COMA = 7;
  public static final int LLAV_IZQ = 4;
  public static final int LLAV_DER = 5;
  public static final int EOF = 0;
  public static final int PR_N = 3;
  public static final int ID = 2;
  public static final int IGUAL = 8;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "PR_N",
  "LLAV_IZQ",
  "LLAV_DER",
  "PT_COMA",
  "COMA",
  "IGUAL"
  };
}

